global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

rule_files:
- django.rules.yml

scrape_configs:
- job_name: django
  static_configs:
    - targets:
      - 167.99.133.164:8000
      - 164.90.234.115:8000
      - 46.101.101.249:8000