# Generated by Django 3.1.3 on 2020-11-17 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionlikes', to='app.answer', verbose_name='Liked answer'),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='is_a_like',
            field=models.IntegerField(choices=[(-1, 'Dislike'), (1, 'Like')], default=-1, verbose_name='Is that a like?'),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='User that liked'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='is_a_like',
            field=models.IntegerField(choices=[(-1, 'Dislike'), (1, 'Like')], default=-1, verbose_name='Is that a like?'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionlikes', to='app.question', verbose_name='Liked question'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='User that liked'),
        ),
    ]
