# Generated by Django 3.1.3 on 2020-11-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201115_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(max_length=256, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
