# Generated by Django 3.1.3 on 2020-11-17 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201117_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerlikes', to='app.answer', verbose_name='Liked answer'),
        ),
    ]
