# Generated by Django 3.1.3 on 2020-11-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201117_2314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('user_id', 'answer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('user_id', 'question_id')},
        ),
    ]
