# Generated by Django 3.1.3 on 2020-11-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201124_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/Toba.jpg', max_length=256, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
