# Generated by Django 3.1.3 on 2020-11-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201125_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='Default Nickname', max_length=32, verbose_name='Nickname'),
        ),
    ]
