# Generated by Django 3.1.3 on 2020-12-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201126_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/Toba.jpg', max_length=256, upload_to='avatars/Xy/Ym/Zd', verbose_name='Avatar'),
        ),
    ]
