# Generated by Django 3.1.3 on 2020-12-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201201_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='is_a_like',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=-1, verbose_name='Is that a like?'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='is_a_like',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=-1, verbose_name='Is that a like?'),
        ),
    ]
